/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.example.events.model.impl;

import com.example.events.model.Participant;
import com.example.events.service.ParticipantLocalServiceUtil;

/**
 * The extended model base implementation for the Participant service. Represents a row in the &quot;Event_Participant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParticipantImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParticipantImpl
 * @see Participant
 * @generated
 */
public abstract class ParticipantBaseImpl
	extends ParticipantModelImpl implements Participant {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a participant model instance should use the <code>Participant</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ParticipantLocalServiceUtil.addParticipant(this);
		}
		else {
			ParticipantLocalServiceUtil.updateParticipant(this);
		}
	}

}