/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.example.events.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Event service. Represents a row in the &quot;Event_Event&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.example.events.model.impl.EventModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.example.events.model.impl.EventImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Event
 * @generated
 */
@ProviderType
public interface EventModel extends BaseModel<Event> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event model instance should use the {@link Event} interface instead.
	 */

	/**
	 * Returns the primary key of this event.
	 *
	 * @return the primary key of this event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event.
	 *
	 * @param primaryKey the primary key of this event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the event ID of this event.
	 *
	 * @return the event ID of this event
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this event.
	 *
	 * @param eventId the event ID of this event
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the title of this event.
	 *
	 * @return the title of this event
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this event.
	 *
	 * @param title the title of this event
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this event.
	 *
	 * @return the description of this event
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this event.
	 *
	 * @param description the description of this event
	 */
	public void setDescription(String description);

	/**
	 * Returns the event date of this event.
	 *
	 * @return the event date of this event
	 */
	public Date getEventDate();

	/**
	 * Sets the event date of this event.
	 *
	 * @param eventDate the event date of this event
	 */
	public void setEventDate(Date eventDate);

	/**
	 * Returns the location of this event.
	 *
	 * @return the location of this event
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this event.
	 *
	 * @param location the location of this event
	 */
	public void setLocation(String location);

	/**
	 * Returns the capacity of this event.
	 *
	 * @return the capacity of this event
	 */
	public int getCapacity();

	/**
	 * Sets the capacity of this event.
	 *
	 * @param capacity the capacity of this event
	 */
	public void setCapacity(int capacity);

	@Override
	public Event cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}