/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.example.events.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Participant service. Represents a row in the &quot;Event_Participant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.example.events.model.impl.ParticipantModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.example.events.model.impl.ParticipantImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Participant
 * @generated
 */
@ProviderType
public interface ParticipantModel extends BaseModel<Participant> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a participant model instance should use the {@link Participant} interface instead.
	 */

	/**
	 * Returns the primary key of this participant.
	 *
	 * @return the primary key of this participant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this participant.
	 *
	 * @param primaryKey the primary key of this participant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the participant ID of this participant.
	 *
	 * @return the participant ID of this participant
	 */
	public long getParticipantId();

	/**
	 * Sets the participant ID of this participant.
	 *
	 * @param participantId the participant ID of this participant
	 */
	public void setParticipantId(long participantId);

	/**
	 * Returns the event ID of this participant.
	 *
	 * @return the event ID of this participant
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this participant.
	 *
	 * @param eventId the event ID of this participant
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the name of this participant.
	 *
	 * @return the name of this participant
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this participant.
	 *
	 * @param name the name of this participant
	 */
	public void setName(String name);

	/**
	 * Returns the email of this participant.
	 *
	 * @return the email of this participant
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this participant.
	 *
	 * @param email the email of this participant
	 */
	public void setEmail(String email);

	@Override
	public Participant cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}